"""Project runtime scaffold for composing system and workspace layers."""

from __future__ import annotations

import json
from pathlib import Path

from sibyl._paths import CLAUDE_RUNTIME_DIR, REPO_ROOT


WORKSPACE_META_DIR = Path(".sibyl")
WORKSPACE_SYSTEM_META = WORKSPACE_META_DIR / "system.json"
WORKSPACE_PROJECT_DIR = WORKSPACE_META_DIR / "project"
WORKSPACE_PROJECT_MEMORY = WORKSPACE_PROJECT_DIR / "MEMORY.md"
WORKSPACE_PROJECT_PROMPT_OVERLAYS = WORKSPACE_PROJECT_DIR / "prompt_overlays"

GENERATED_CLAUDE_HEADER = "<!-- GENERATED BY SIBYL. Edit .sibyl/project/MEMORY.md instead. -->"

_DEFAULT_PROJECT_MEMORY = """# Project Memory

记录这个项目特有的长期约束、偏好和已确认决策。

- 这里只写项目层信息，不要重复系统层规则
- 长期有效的约束优先，例如数据集、资源预算、论文目标、禁用方案
- 当系统策略与项目特殊要求冲突时，在这里明确写出覆盖规则
"""


def _is_link_or_junction(path: Path) -> bool:
    """Return True if *path* is a symlink or a Windows junction."""
    if path.is_symlink():
        return True
    if hasattr(path, "is_junction") and path.is_junction():
        return True
    return False


def _ensure_symlink(link_path: Path, target_path: Path) -> None:
    """Create a symlink (or junction on Windows) when the target exists and the link is still unmanaged."""
    import sys
    if not target_path.exists():
        return
    if _is_link_or_junction(link_path):
        try:
            if link_path.resolve() == target_path.resolve():
                return
        except OSError:
            pass
        return
    if link_path.exists():
        return
    link_path.parent.mkdir(parents=True, exist_ok=True)
    if sys.platform == "win32":
        # On Windows, symlinks require admin privileges; use junction for dirs,
        # or copy for files as fallback.
        import shutil
        import subprocess
        target_resolved = target_path.resolve()
        if target_resolved.is_dir():
            try:
                # Try junction first (no admin needed)
                subprocess.run(
                    ["cmd", "/c", "mklink", "/J", str(link_path), str(target_resolved)],
                    check=True, capture_output=True,
                )
            except (subprocess.CalledProcessError, FileNotFoundError):
                # Fall back to copying directory
                shutil.copytree(str(target_resolved), str(link_path))
        else:
            shutil.copy2(str(target_resolved), str(link_path))
    else:
        link_path.symlink_to(target_path)


def detect_workspace_root(candidate: str | Path | None = None) -> Path | None:
    """Best-effort runtime detection for a Sibyl project workspace."""
    if candidate is None:
        import os

        candidate = os.environ.get("SIBYL_WORKSPACE")
    start = Path(candidate or Path.cwd()).expanduser()
    try:
        start = start.resolve()
    except OSError:
        start = start.absolute()

    for current in (start, *start.parents):
        if (current / WORKSPACE_SYSTEM_META).exists():
            return current
        if current.name == "current" and (current.parent / "status.json").exists():
            return current.parent
        if (current / "status.json").exists():
            return current
    return None


def project_memory_path(workspace_root: str | Path | None = None) -> Path | None:
    """Return the project memory file when a workspace can be resolved."""
    root = detect_workspace_root(workspace_root)
    if root is None:
        return None
    return root / WORKSPACE_PROJECT_MEMORY


def project_prompt_overlay_path(
    agent_name: str,
    workspace_root: str | Path | None = None,
) -> Path | None:
    """Return the project overlay file for an agent when available."""
    root = detect_workspace_root(workspace_root)
    if root is None:
        return None
    return root / WORKSPACE_PROJECT_PROMPT_OVERLAYS / f"{agent_name}.md"


def load_project_memory(workspace_root: str | Path | None = None) -> str:
    """Read project-level memory that should be appended to common instructions."""
    memory_path = project_memory_path(workspace_root)
    if memory_path is None or not memory_path.exists():
        return ""
    return memory_path.read_text(encoding="utf-8").strip()


def load_project_prompt_overlay(
    agent_name: str,
    workspace_root: str | Path | None = None,
) -> str:
    """Read an agent-specific project overlay when present."""
    overlay_path = project_prompt_overlay_path(agent_name, workspace_root)
    if overlay_path is None or not overlay_path.exists():
        return ""
    return overlay_path.read_text(encoding="utf-8").strip()


def _render_workspace_claude_md(workspace_root: Path, system_root: Path) -> str:
    system_claude_path = system_root / "CLAUDE.md"
    system_text = ""
    if system_claude_path.exists():
        system_text = system_claude_path.read_text(encoding="utf-8").rstrip()

    project_memory = load_project_memory(workspace_root)
    lines = [
        GENERATED_CLAUDE_HEADER,
        f"<!-- System source: {system_claude_path} -->",
        f"<!-- Project memory source: {workspace_root / WORKSPACE_PROJECT_MEMORY} -->",
        "",
        system_text,
        "",
        "## Project Memory Layer",
        "",
        project_memory or "_No project-specific memory yet. Edit `.sibyl/project/MEMORY.md`._",
        "",
    ]
    return "\n".join(lines)


def ensure_workspace_runtime_assets(
    workspace_root: str | Path,
    system_root: Path = REPO_ROOT,
) -> None:
    """Materialize the effective runtime view for a project workspace.

    System-owned assets are linked from the Sibyl repo so skills/prompts keep
    hot-reloading. Project-owned memory stays inside the workspace.
    """
    root = Path(workspace_root)
    root.mkdir(parents=True, exist_ok=True)

    (root / WORKSPACE_PROJECT_PROMPT_OVERLAYS).mkdir(parents=True, exist_ok=True)
    project_memory = root / WORKSPACE_PROJECT_MEMORY
    if not project_memory.exists():
        project_memory.write_text(_DEFAULT_PROJECT_MEMORY, encoding="utf-8")

    system_meta = {
        "system_root": str(system_root.resolve()),
        "workspace_root": str(root.resolve()),
        "version": 1,
    }
    meta_path = root / WORKSPACE_SYSTEM_META
    meta_path.parent.mkdir(parents=True, exist_ok=True)
    meta_path.write_text(
        json.dumps(system_meta, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    _ensure_symlink(root / ".venv", system_root / ".venv")
    _ensure_symlink(root / ".claude" / "agents", CLAUDE_RUNTIME_DIR / "agents")
    _ensure_symlink(root / ".claude" / "skills", CLAUDE_RUNTIME_DIR / "skills")
    _ensure_symlink(
        root / ".claude" / "settings.local.json",
        CLAUDE_RUNTIME_DIR / "settings.local.json",
    )

    claude_path = root / "CLAUDE.md"
    rendered = _render_workspace_claude_md(root, system_root)
    if not claude_path.exists() or claude_path.read_text(encoding="utf-8").startswith(
        GENERATED_CLAUDE_HEADER
    ):
        claude_path.write_text(rendered, encoding="utf-8")
